version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    labels:
      - "priority: medium"
      - "type: dependency"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    labels:
      - "priority: medium"
      - "type: dependency"
