default_language_version:
  python: python3.11

repos:
  - repo: "https://github.com/PyCQA/pylint"
    rev: v3.1.0
    hooks:
      - id: pylint
  - repo: "https://github.com/bwhmather/ssort"
    rev: 0.12.4
    hooks:
      - id: ssort
  - repo: "https://github.com/charliermarsh/ruff-pre-commit"
    rev: v0.3.5
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies: ["arcade==3.0.0.dev24", "pytest==7.4.0"]
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.6.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        args: ["--autofix"]
      - id: trailing-whitespace
  - repo: "https://github.com/psf/black"
    rev: 24.3.0
    hooks:
      - id: black
