default_language_version:
    python: python3.10

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: pretty-format-json
        args: ["--autofix"]
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
    -   id: pyupgrade
        args: ["--py310-plus"]
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        args: ["--preview"]
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    -   id: mypy
        args: ["--ignore-missing-imports"]
#-   repo: https://github.com/PyCQA/docformatter
#    rev: v1.4
#    hooks:
#    -   id: docformatter
#        args: ["--in-place", "--wrap-summaries", "88", "--wrap-descriptions", "88"]
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: ["--max-line-length=88", "--ignore=E203,W503", "--enable-extensions=W504"]
        additional_dependencies:
            -   flake8-bugbear
            -   flake8-builtins
            -   flake8-comprehensions
            -   flake8-dunder-all
            -   flake8-encodings
            -   flake8-logging-format
            -   flake8-pep585
            -   flake8-pie
            -   flake8-return
            -   flake8-simplify
            -   flake8-type-checking
            -   pep8-naming
#-   repo: https://github.com/PyCQA/pylint
#    rev: v2.14.3
#    hooks:
#    -   id: pylint
#        args: [
#            "--disable=E0001,E1123,E1120,R0914,R0915,E0611,R0902,R0901,E1101,R0913,C0302,R0904,E0401,R0903,C0103,W0201,W0235,R1705,C0415",
#            "--max-line-length=88",
#            "--good-names=i,j,k,x,y,dx,dy,x1,x2,y1,y2",
#            "--ignore=TEMP-FILES",
#            "--load-plugins=pylint.extensions.emptystring,
#            pylint.extensions.comparison_placement,
#            pylint.extensions.confusing_elif,
#            pylint.extensions.for_any_all,
#            pylint.extensions.consider_ternary_expression,
#            pylint.extensions.bad_builtin,
#            pylint.extensions.check_elif
#            pylint.extensions.set_membership",
#        ]

# Flake8 codes:
# - E203 is flake8 complaining about a whitespace before a colon in bsp.py
# - W503 is flake8 wanting to put an operator on the next line (not preferred due to black)
# - W504 is flake8 wanting to put an operator on the same line (preferred due to black)

# Pylint codes:
# - E0001 is pylint not recognising match-case
# - E1123 is pylint not recognising kw_only for dataclasses.field
# - E1120 is pylint not understanding attack_type is set instead the dataclass
# - R0914 is too many local variables for the create_hallway function. I'm planning to redo it at some point
# - R0915 is too many statements for the create_hallway function. I'm planning to redo it at some point
# - E0611 is pylint not recognising the pairwise import in the itertools library
# - R0902 is pylint complaining about too many instance attributes
# - R0901 is pylint complaining about the inheritance tree being too big
# - E1101 is pylint not discovering the arcade.Texture.create_filled class method
# - R0913 is pylint complaining about too many parameters
# - C0302 is pylint complaining about too many lines
# - R0904 is pylint complaining about too many public methods
# - E0401 is pylint not being able to import packages
# - R0903 is pylint complaining about too few public methods
# - C0103 is pylint complaining about snake_case
# - W0201 is pylint complaining about attributes being defined outside __init__ (when I need them to be)
# - W0235 is pylint complaining about super().__init__ not being needed in some places
# - R1705 is pylint complaining about an else being after a return
# - C0415 is pylint complaining about the constants.entity imports in attack.py
