[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "hades"
version = "0.1.0"
description = "A procedurally generated bullet bullet-hell dungeon crawler made in Python."
authors = ["Aspect1103 <jack.ashwell1@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Aspect1103/Hades"
repository = "https://github.com/Aspect1103/Hades"
packages = [
    { include = "hades", from = "python_src" }
]

[tool.poetry.build]
# generate-setup-file = false
script = "build.py"

[tool.poetry.dependencies]
python = "^3.10"
arcade = "2.6.16"
maturin = "0.14.6"
numpy = "1.23.5"
pybind11 = "2.10.3"
pymunk = "6.2.1"
shapely = "2.0.0"

[tool.poetry.dev-dependencies]
bandit = "1.7.4"
black = "22.12.0"
flake8 = "6.0.0"
isort = "5.11.1"
mypy = "v0.991"
nuitka = "1.2.6"
ordered-set = "4.1.0"
pre-commit = "2.20.0"
pydocstyle = "6.1.1"
pylint = "v2.15.6"
pytest = "7.2.0"
pytest-cov = "4.0.0"
pytest-icdiff = "0.6"
pytest-instafail = "0.4.2"
pytest-randomly = "3.12.0"
pytest-sugar = "0.9.6"
pyupgrade = "v3.2.2"
ssort = "v0.11.6"
tox = "4.0.8"

[tool.bandit]
skips = [
    "B101",  # Allow assert statements (useful for mypy)
    "B311",  # Allow use of the random library
    "B404",  # Allow use of the subprocess library
    "B603",  # Allow use of subprocess.run with shell=True
    "B607",  # Allow use of subprocess calling `maturin develop`
]

[tool.black]
preview = true
target_version = ["py310"]

[tool.coverage.paths]
source = [
    "python_src",
    ".tox/*/Lib/site-packages",
    ".tox/*/lib/*/site-packages",
]

[tool.coverage.report]
exclude_lines = [
    "if TYPE_CHECKING:",  # Exclude all type checking imports
    "pragma: no cover",  # Exclude all no cover blocks
    "raise NotImplementedError",  # Exclude all base functions
    "if __name__ == .__main__.:",  # Exclude script definitions
]
omit = [
    "*/__main__.py",  # This is only used for running the game via the CLI
    "*/extensions/compile.py",  # This is only used for building the C++ extensions
]
precision = 2
show_missing = true

[tool.coverage.run]
branch = true
source = ["hades"]

[tool.isort]
filter_files = true
profile = "black"

[tool.mypy]
# TODO: Once Arcade releases 2.7 (or a bugfix release with types), these flags can be
#  re-evaluated to get strict mypy typing
#disallow_any_explicit = true
#disallow_subclassing_any = true
#disallow_untyped_calls = true
#disallow_untyped_decorators = true
#warn_return_any = true
#warn_unused_ignores = true

check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
exclude = [
    "inventory_view.py"
]
ignore_missing_imports = true
no_implicit_reexport = true
pretty = true
python_version = "3.10"
show_column_numbers = true
show_error_context = true
strict_concatenate = true
strict_equality = true
warn_redundant_casts = true
warn_unused_configs = true

[tool.pydocstyle]
convention = "numpy"

[tool.pylint."BASIC"]
good-names = "i,j,k,x,y,a,b,dx,dy,x1,x2,y1,y2"

[tool.pylint."FORMAT"]
max-line-length = 88

[tool.pylint."MASTER"]
ignore = "TEMP-FILES"
load-plugins = [
    "pylint.extensions.bad_builtin",  # Disallow the use of deprecated builtin functions
    "pylint.extensions.check_elif",  # Disallow the use of following an else statement with an if
    "pylint.extensions.comparison_placement",  # Disallow placing the constant on the left of the comparison
    "pylint.extensions.confusing_elif",  # Disallow placing an elif after an indented block (could be hard to understand)
    "pylint.extensions.consider_ternary_expression",  # Disallow spreading multiple assignment statements across if/else blocks
    "pylint.extensions.emptystring",  # Disallow comparisons to empty strings
    "pylint.extensions.for_any_all",  # Disallow using a for loop to check for a condition and return a bool
    "pylint.extensions.set_membership",  # Disallow not using sets for membership tests
]

[tool.pylint."MESSAGES CONTROL"]
enable = "useless-suppression"
disable = [
    "attribute-defined-outside-init",  # Allow attributes being defined outside __init__ (sometimes this needs to happen)
    "import-error",  # Sometimes pylint can't import a package correctly
    "no-else-return",  # Allow else statement after a return
    "no-member",  # Allow BaseView to set the window attribute
    "no-name-in-module",  # Pylint can't infer imports from the extensions
    "redefined-outer-name",  # Allow redefining outer names (this is used in pytest)
    "too-few-public-methods",  # Stop Pylint complaining about too few public methods
    "too-many-arguments",  # Stop Pylint complaining about too many parameters
    "too-many-instance-attributes",  # Stop Pylint complaining about too many instance attributes
    "too-many-locals",  # Stop Pylint complaining about too many local variables
    "too-many-statements",  # Stop Pylint complaining about too many statements
]

[tool.pytest.ini_options]
addopts = "-vv -ra --showlocals --cov --cov-report term-missing"
testpaths = ["tests"]

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = clean, py310, report
isolated_build = true

[gh-actions]
python =
    3.10: clean, py310, report

[testenv]
deps = pytest-cov
commands =
    python -I -m hades.extensions.compile
    pytest --cov-append

[testenv:clean]
deps = pytest-cov
commands = coverage erase

[testenv:report]
deps = pytest-cov
commands = coverage lcov
"""
