[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "game"  # TODO: CHANGE GAME NAME AND GAME/ DIR BE THE NEW NAME
version = "0.0.1"
description = "A procedurally generated dungeon crawler made in Python."
authors = ["Aspect1103 <jack.ashwell1@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Aspect1103/Procedurally-Generated-Dungeon-Crawler"
repository = "https://github.com/Aspect1103/Procedurally-Generated-Dungeon-Crawler"

[tool.poetry.dependencies]
python = "^3.10"
arcade = "2.6.15"
numpy = "1.23.1"
pymunk = "6.2.1"
shapely = "1.8.2"

[tool.poetry.dev-dependencies]
nuitka = "1.0.1"
pre-commit = "2.20.0"
pytest = "7.1.2"
pytest-cov = "3.0.0"
pytest-icdiff = "0.5"
pytest-instafail = "0.4.2"
pytest-randomly = "3.12.0"
pytest-sugar = "0.9.5"
tox = "3.25.1"

[tool.pytest.ini_options]
addopts = "-vv --cov=game --cov-report=term-missing"
testpaths = ["tests"]

[tool.coverage.report]
exclude_lines = [
    "if TYPE_CHECKING:",  # Exclude all type checking imports
]

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = true
envlist = clean, py310, report

[testenv]
allowlist_externals = poetry
commands = poetry run pytest --cov-append

[testenv:clean]
allowlist_externals = coverage
commands = coverage erase

[testenv:report]
allowlist_externals = coverage
commands = coverage lcov
"""
