name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10"]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install tox tox-gh-actions
      - name: Run Tox
        run: tox
      - name: Upload coverage report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.lcov
          parallel: true
  test-cpp:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        if: ${{ matrix.os }} == "windows-latest"
      - name: Set up CMake
        uses: lukka/get-cmake@latest
      - name: Configure and build CMake
        uses: lukka/run-cmake@v3
        env:
          ENV_DIR: "${{ github.workspace }}"
        with:
          cmakeListsTxtPath: "${{ github.workspace }}/cpp_src/CMakeLists.txt"
      - name: Run CTest
        run: ctest --output-on-failure
  coveralls:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coverage report finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
