name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1.13.0
      - name: Set up CMake
        uses: lukka/get-cmake@v3.29.5
      - name: Install EGL on Linux for headless Arcade
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install libegl1
      - name: Run Nox
        run: pipx run nox --error-on-missing-interpreters -s tests-${{ matrix.python-version }}
      - name: Upload coverage report
        uses: coverallsapp/github-action@v2.3.0
        with:
          file: coverage.lcov
          flag-name: run-python-${{ matrix.os }}-${{ matrix.python-version }}
          parallel: true
  cpp:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            cmake-preset: WinDebug
          - os: ubuntu-latest
            cmake-preset: LinuxDebug
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6
        with:
          submodules: recursive
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1.13.0
      - name: Set up CMake
        uses: lukka/get-cmake@v3.29.5
      - name: Build CMake and run CTest
        working-directory: ${{ github.workspace }}/src/hades_extensions
        run: |
          cmake -DDO_PYTHON=OFF --preset ${{ matrix.cmake-preset }}
          cmake --build build-debug
          ctest --output-on-failure --no-tests=error --test-dir ${{ github.workspace }}/src/hades_extensions/build-debug/tests
      - name: Generate the coverage report
        if: matrix.os == 'ubuntu-latest'
        run: |
          pip install gcovr
          gcovr -r ${{ github.workspace }} --exclude src/hades_extensions/build-debug --exclude src/hades_extensions/tests --exclude src/hades_extensions/src/binding.cpp --coveralls coverage.json
      - name: Upload coverage report
        if: matrix.os == 'ubuntu-latest'
        uses: coverallsapp/github-action@v2.3.0
        with:
          file: coverage.json
          flag-name: run-cpp-${{ matrix.os }}
          parallel: true
  finish:
    runs-on: ubuntu-latest
    needs: [python, cpp]
    steps:
      - name: Upload coverage report
        uses: coverallsapp/github-action@v2.3.0
        with:
          parallel-finished: true
